name: Swiftformat

on:
  pull_request:
    paths:
      - '.github/workflows/swiftformat.yml'
      - '.swiftformat.yml'
      - '**/*.swift'


jobs:
    swiftformat:
      name: Check swiftformat
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
          with:
            submodules: recursive
  
        - name: Update PATH
          run: echo ::add-path::$HOME/bin
  
        - name: Cache packages/Tools/.build
          uses: actions/cache@v1
          with:
            path: packages/Tools/.build
            key: ${{ runner.os }}-swift-tools-build-${{ hashFiles('packages/Tools/Package.resolved') }}
            restore-keys: |
              ${{ runner.os }}-swift-tools-build-
        - name: Cache ~/bin
          uses: actions/cache@v1
          with:
            path: ~/bin
            key: ${{ runner.os }}-home-bin-${{ hashFiles('packages/Tools/Package.resolved') }}
            restore-keys: |
              ${{ runner.os }}-home-bin-
        - name: Install Swift tools
          run: make swift-tools
  
        - name: Format Swift code
          run: swiftformat --verbose .
  
        - name: Verify formatted code is unchanged
          run: git diff --exit-code HEAD